### ISSUE TITLE
json example?

### ISSUE THREAD

**Issue by persianphilosopher** [HerrHase/fuzzy-cms#1]
Hi there,
Thank you for making this project. It's very much the kind that I have been looking for but I must confess that I have struggled getting it going and it seems that it's due to the json file.  Would it be possible to have a plain example of index.md and its json?

And I am not sure whether the following matters but just in case: out of habit, I typed "php artisan" and it gave me this:
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Memcached' not found
```
Thanks again

**Comment by nirgendswo** [comment]
Hi,
good idea, i have add a simple Example in the README.md in section 4.3

To deal with the Error there a some proposals,

* check if you have installed php-memcached and the config in php.ini is correct
* restart server
* as Workaround some add "CACHE_DRIVER=file" in there .env-file

Kind regards
```

**Comment by persianphilosopher** [comment]
Thank you, truly, for your prompt response. I had not realized that the md file contained the json by itself!

I made sure that memcached is installed and enabled and even tried your suggested workaround. This is the log that I get: [pastebin](https://pastebin.com/SwmjKWV7).

I put it as a paste so that I could include the entire file.

**Comment by nirgendswo** [comment]
Ah, my fault, in the default template the navigation.blade.php uses svg-icons that a named in the json, add this to the json,

```
"icon": "shop"
```
